name: Database Backup Cron

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  backup-job:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Add Focal security repo and install libssl1.1
        run: |
          echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list
          sudo apt-get update
          sudo apt-get install -y libssl1.1

      - name: Install PostgreSQL 17 tools
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main 17" > /etc/apt/sources.list.d/pgdg.list'
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Install MongoDB Tools
        run: |
          curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-server.gpg
          echo "deb [ signed-by=/usr/share/keyrings/mongodb-server.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-database-tools

      - name: Install dependencies
        run: npm install

      - name: Run backup script (MongoDB and PostgreSQL)
        run: node index.js
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          OUTPUT_DIR: ${{ secrets.OUTPUT_DIR }}
          SOURCE_URI: ${{ secrets.SOURCE_URI }}
          DEST_URI: ${{ secrets.DEST_URI }}
          B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
          B2_ACCOUNT_ID: ${{ secrets.B2_ACCOUNT_ID }}
          B2_BUCKET_ID: ${{ secrets.B2_BUCKET_ID }}
          SOURCE_NEON_URI: ${{ secrets.SOURCE_NEON_URI }}
          DEST_NEON_URI: ${{ secrets.DEST_NEON_URI }}
